remote_theme : mmistakes/minimal-mistakes
# Site Settings
locale                   : "ko-korea"
title                    : "TEST"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "moongunwho"
description              : "An amazing website."
url                      : "https://who307.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : who307/practice